In [53]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler,OneHotEncoder
from sklearn.impute import SimpleImputer
from sklearn.ensemble import RandomForestClassifier

In [54]:
x_train=pd.read_csv("/content/x_train")
x_test=pd.read_csv("/content/x_test")
y_train=pd.read_csv("/content/y_train")
y_test=pd.read_csv("/content/y_test")

In [55]:
x_train=x_train[['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area']]
x_train

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,No,0.0,Not Graduate,No,1442,0.0,35.0,360.0,1.0,Urban
1,Male,Yes,0.0,Graduate,No,3948,1733.0,149.0,360.0,0.0,Rural
2,Male,No,0.0,Graduate,Yes,20166,0.0,650.0,480.0,NaN,Urban
3,Male,Yes,1.0,Graduate,No,8300,0.0,152.0,300.0,0.0,Semiurban
4,Male,No,0.0,Graduate,No,3158,3053.0,89.0,360.0,1.0,Rural
...,...,...,...,...,...,...,...,...,...,...,...
473,Male,Yes,1.0,Graduate,Yes,2895,0.0,95.0,360.0,1.0,Semiurban
474,Male,No,0.0,Not Graduate,No,3748,1668.0,110.0,360.0,1.0,Semiurban
475,Female,No,0.0,Graduate,No,4160,0.0,71.0,360.0,1.0,Semiurban
476,Male,No,0.0,Graduate,No,3167,0.0,74.0,360.0,1.0,Urban
477,Female,No,0.0,Graduate,Yes,7441,0.0,194.0,360.0,1.0,Rural

In [56]:
x_test=x_test[['Gender','Married','Dependents','Education','Self_Employed','ApplicantIncome','CoapplicantIncome','LoanAmount','Loan_Amount_Term','Credit_History','Property_Area']]
x_test

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,Male,Yes,2.0,Graduate,No,3159,461.0,108.0,84.0,1.0,Urban
1,Male,Yes,0.0,Graduate,No,3859,3300.0,142.0,180.0,1.0,Rural
2,Male,Yes,0.0,Graduate,No,3887,2669.0,162.0,360.0,1.0,Semiurban
3,Female,No,0.0,Graduate,No,2378,0.0,9.0,360.0,1.0,Urban
4,Male,Yes,2.0,Graduate,No,6250,1695.0,210.0,360.0,1.0,Semiurban
...,...,...,...,...,...,...,...,...,...,...,...
115,Male,Yes,3.0,Graduate,Yes,4416,1250.0,110.0,360.0,1.0,Urban
116,Male,Yes,2.0,Graduate,No,8333,0.0,246.0,360.0,1.0,Semiurban
117,Male,Yes,2.0,Graduate,Yes,5000,0.0,72.0,360.0,0.0,Semiurban
118,Female,Yes,0.0,Graduate,No,3416,2816.0,113.0,360.0,NaN,Semiurban
119,Male,Yes,2.0,Graduate,No,4566,0.0,100.0,360.0,1.0,Urban

In [57]:
y_train=y_train[['Loan_Status']]
y_train

     Loan_Status
0              0
1              0
2              1
3              0
4              1
..           ...
473            1
474            1
475            1
476            0
477            0

[478 rows x 1 columns]

In [58]:
y_test=y_test[['Loan_Status']]
y_test

     Loan_Status
0              1
1              1
2              1
3              0
4              1
..           ...
115            1
116            1
117            0
118            1
119            0

[120 rows x 1 columns]

In [59]:
numeric_features = [
    "ApplicantIncome",
    "CoapplicantIncome",
    "LoanAmount",
    "Loan_Amount_Term",
    "Credit_History"
]

categorical_features = [
    "Gender",
    "Married",
    "Dependents",
    "Education",
    "Self_Employed",
    "Property_Area"
]

In [60]:
numeric_pipeline = Pipeline(
    steps=[
        ( "imputer",
            SimpleImputer(strategy="median")
        ),
        (
            "scaler",
            StandardScaler()
        )
    ]
)

In [61]:
categorical_pipeline = Pipeline(
    steps=[
        (
            "imputer",
            SimpleImputer(
                strategy="most_frequent"
            )
        ),
        (
            "encoder",
            OneHotEncoder(
                handle_unknown="ignore"
            )
        )
    ]
)

In [62]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            numeric_pipeline,
            numeric_features
        ),
        (
            "cat",
            categorical_pipeline,
            categorical_features
        )
    ]
)

In [63]:
model_pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),
        (
            "model",
            RandomForestClassifier(
                n_estimators=100,
                random_state=42
            )
        )
    ]
)

In [64]:
model_pipeline.fit(x_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['ApplicantIncome',
                                                   'CoapplicantIncome',
                                                   'LoanAmount',
                                                   'Loan_Amount_Term',
                                                   'Credit_History']),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'Married',
                                                   'Dependents', 'Education',
                                                   'Self_Employed',
                                                   'Property_Area'])])),
                ('model', RandomForestClassifier(random_state=42))])

In [65]:
y_pred = model_pipeline.predict(x_test)

In [66]:
y_pred

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 0, 1, 1])

In [67]:
y_test

     Loan_Status
0              1
1              1
2              1
3              0
4              1
..           ...
115            1
116            1
117            0
118            1
119            0

[120 rows x 1 columns]

In [68]:
from sklearn.metrics import accuracy_score, classification_report

accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)
print(classification_report(y_test, y_pred))

Accuracy: 0.8166666666666667
              precision    recall  f1-score   support

           0       0.90      0.47      0.62        38
           1       0.80      0.98      0.88        82

    accuracy                           0.82       120
   macro avg       0.85      0.72      0.75       120
weighted avg       0.83      0.82      0.80       120

In [70]:
import os
import joblib


os.makedirs("models", exist_ok=True)

joblib.dump(
    model_pipeline,
    "models/loan_approval_model.pkl"
)

print("Model saved successfully!")

Model saved successfully!